package com.corbin;

public enum TokenType {

    IDENTIFIER, NUMBER, STRING,

    KW_INT, KW_FLOAT, KW_STRING, KW_TRUE, KW_FALSE, KW_FUNC, KW_VOID, KW_VAR, KW_CONST, KW_FOR, KW_IN, KW_WHILE, KW_IF,
    KW_ELSE, KW_SWITCH, KW_CASE, KW_DEFAULT,

    OP_NOT, OP_PLUS, OP_MINUS, OP_TIMES, OP_DIVIDE, OP_EXP, OP_MOD, OP_INCREMENT, OP_DECREMENT, OP_GREATER, OP_GREATEREQUAL,
    OP_EQUAL, OP_NOTEQUAL, OP_LESS, OP_LESSEQUAL, OP_RETURNS, OP_ASSIGN, OP_PLUSASSIGN, OP_MINUSASSIGN, OP_TIMESASSIGN,
    OP_DIVIDEASSIGN, OP_MODASSIGN, OP_EXPASSIGN, OP_AND, OP_OR, OP_ELLIPSIS,

    PUNC_OPENPAREN, PUNC_CLOSEPAREN, PUNC_OPENBRACE, PUNC_CLOSEBRACE, PUNC_COMMAN, PUNC_COLON, PUNC_SEMICOLON, PUNC_PERIOD,
    PUNC_OPENBRACKET, PUNC_CLOSEBRACKET

}
